### PR TITLE
Added 10.1.1, SXA, XM support

### PR DESCRIPTION
**Pull request by cheeto-bandito**
I have tested this against a local and Azure PaaS Sitecore XP 10.1.1 instance with SXA installed using a SearchStax free plan (Account: ADOE5TSFJQ) with no issues.  I do not have the ability to test this against a Commerce installation.  Please let me know if you'd like me to test anything additional / provide artifacts.

### CODE REVIEW

**Comment by cheeto-bandito** [comment]
Friendly nudge on this PR @dkapoor and @karanjeetsingh

**Comment by cheeto-bandito** [comment]
Friendly nudge on this PR… @dkapoor , @karanjeetsingh, @maggon

**Comment by maggon** [comment]
Hi Chet, thanks for the nudge, we'll prioritize this now and get back!

**Comment by cheeto-bandito** [comment]
@maggon Linked to issue #21.  Would love to continue contributing if I can get an approval or feedback on this PR.

**Comment by hugosantos-konabos** [comment]
Hi @cheeto-bandito,

It looks like your code handling SXA indexes the same way the plugin handles **non**-SXA indexes, which is adding the **configured prefix** at the beginning of the index core name.

It makes sense to **non**-SXA indexes since Sitecore adds this prefix to the index core name:

image

However, when it comes to SXA indexes if you take a look at the index configuration you are going to see that the **core name is exactly the same as the core id, without any prefix**:

image

I'd suggest you handle $collectionsSXA differently instead of just adding it to $globals:coll. By doing that, it's going to be super easy to remove the prefix before calling SearchStax to push index configuration and create the collection.
image

image

**Comment by cheeto-bandito** [comment]
> Hi @cheeto-bandito,
> 
> It looks like your code handling SXA indexes the same way the plugin handles **non**-SXA indexes, which is adding the **configured prefix** at the beginning of the index core name.
> 
> It makes sense to **non**-SXA indexes since Sitecore adds this prefix to the index core name:
> 
> image
> 
> However, when it comes to SXA indexes if you take a look at the index configuration you are going to see that the **core name is exactly the same as the core id, without any prefix**:
> 
> image
> 
> I'd suggest you handle $collectionsSXA differently instead of just adding it to $globals:coll. By doing that, it's going to be super easy to remove the prefix before calling SearchStax to push index configuration and create the collection.
> image
> 
> image

I think Sitecore will remedy this oversight in making consistency in future releases.  I’ll split this into separate PRs:

1. 10.1.1 support
2. SXA support

**Comment by hugosantos-konabos** [comment]
Hi @cheeto-bandito,

Do you have an ETA in mind for that? I can definitely help with any one of those two PRs.

**Comment by cheeto-bandito** [comment]
@hugosantos-konabos I actually have 3 functional pieces of work completed that I'm using today
with a client:

1. Sitecore 10.1.1 support
2. SXA Support
3. XM topology support

My challenge is testing those three features independently for ease of PR
review and trying to find a way to introduce some reusable commandlets
without creating a refactoring nightmare.  If you're ok with reviewing one
big PR, I can have this to you today.  If you'd like bite-sized chunks,
it'll take me until the end of the week to cherry-pick.

**Comment by hugosantos-konabos** [comment]
Hi @cheeto-bandito,

I can test it all together, no problem. A single PR is fine.

**Comment by cheeto-bandito** [comment]
@hugosantos-konabos All set.

**Comment by hugosantos-konabos** [comment]
Tested and approved.

**Pull request merged**
